/**
 * VYAVSAYMITRA — Authoritative Sourced Initial Formula Library
 * 
 * Contains verified formulas from statutory, government, and institutional sources:
 * 1. Government of India / Ministries (MoAFW, MoFPI, MSME)
 * 2. CACP (Commission for Agricultural Costs & Prices)
 * 3. DES (Directorate of Economics & Statistics)
 * 4. NABARD (National Bank for Agriculture and Rural Development)
 * 5. ICAR (Indian Council of Agricultural Research) & CSIR-CFTRI
 * 6. Statutory Accounting & Costing Standards (ICAI, ICMAI, RBI)
 * 
 * Non-validated or uncalibrated formulas are strictly marked RESEARCH_REQUIRED.
 */

const { FORMULA_STATUSES } = require('./formulaSchema');

const INITIAL_PARAMETERS = [
  // Financial Parameters
  {
    parameterId: 'selling_price',
    name: 'Selling Price per Unit',
    description: 'Realized market selling price per unit of goods or service',
    dataType: 'number',
    unit: 'INR/unit',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'Verified Mandi / Market Reference or Entrepreneur Input',
    sourceDate: '2024-2026',
    dataStatus: 'VERIFIED_DATA',
    userInputAllowed: true
  },
  {
    parameterId: 'quantity_sold',
    name: 'Quantity Sold',
    description: 'Volume of goods or services sold within operating period',
    dataType: 'number',
    unit: 'units',
    currency: null,
    required: true,
    minimum: 0,
    source: 'Operational Capacity / Entrepreneur Input',
    sourceDate: '2024-2026',
    dataStatus: 'USER_INPUT',
    userInputAllowed: true
  },
  {
    parameterId: 'fixed_cost',
    name: 'Total Fixed Cost',
    description: 'Fixed structural operating expenses independent of production volume (rent, permanent labor, insurance, depreciation)',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'ICMAI CAS-1 Cost Classification',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'variable_cost',
    name: 'Total Variable Cost',
    description: 'Operational expenses directly scaling with production (raw material, power, packaging, piece-rate labor)',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'ICMAI CAS-1 Cost Classification',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'variable_cost_per_unit',
    name: 'Variable Cost per Unit',
    description: 'Variable cost incurred per individual unit of output produced',
    dataType: 'number',
    unit: 'INR/unit',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'Process Costing Benchmark',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'initial_investment',
    name: 'Initial Capital Investment',
    description: 'Total project setup capital including plant, machinery, civil works, and pre-operative expenses',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'NABARD / PMEGP Project Profiles',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'annual_operating_cost',
    name: 'Annual Operating Cost',
    description: 'Total annual operational expenditure (fixed + variable)',
    dataType: 'number',
    unit: 'INR/year',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'Annual Operating Budget',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'operating_cycle_days',
    name: 'Operating Cycle Days',
    description: 'Average days elapsed from raw material procurement to final cash collection',
    dataType: 'number',
    unit: 'days',
    currency: null,
    required: true,
    minimum: 1,
    maximum: 365,
    source: 'RBI Tandon / Nayak Committee Working Capital Norms',
    sourceDate: '2024-2026',
    dataStatus: 'VERIFIED_DATA',
    userInputAllowed: true
  },

  // Agriculture Parameters
  {
    parameterId: 'area_ha',
    name: 'Cultivation Area',
    description: 'Net operational cropped land area in hectares',
    dataType: 'number',
    unit: 'hectare',
    currency: null,
    required: true,
    minimum: 0.1,
    maximum: 1000,
    source: 'Land Record / Farmer Declaration',
    sourceDate: '2024-2026',
    dataStatus: 'USER_INPUT',
    userInputAllowed: true
  },
  {
    parameterId: 'yield_tonnes_per_ha',
    name: 'Crop Yield per Hectare',
    description: 'Average crop harvest output per hectare',
    dataType: 'number',
    unit: 'tonnes/ha',
    currency: null,
    required: true,
    minimum: 0,
    source: 'Directorate of Economics & Statistics (DES) Census Baselines',
    sourceDate: '1997-2020',
    dataStatus: 'VERIFIED_DATA',
    userInputAllowed: true
  },
  {
    parameterId: 'paid_out_operational_expenses',
    name: 'Paid-Out Operational Expenses (Cost A1)',
    description: 'Direct cash expenses on hired human labour, bullock labour, machine labour, seeds, fertilizers, manure, pesticides, irrigation, fuel, and depreciation on farm equipment',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'CACP Cost Concepts Methodology',
    sourceDate: '2024-2025',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'rent_paid_leased_in_land',
    name: 'Rent Paid for Leased-in Land',
    description: 'Actual contractual cash or produce rent paid for leased farmland',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'Farmer Lease Agreement / CACP Survey',
    sourceDate: '2024-2025',
    dataStatus: 'USER_INPUT',
    userInputAllowed: true
  },
  {
    parameterId: 'imputed_family_labour_value',
    name: 'Imputed Value of Family Labour',
    description: 'Economic value of unpaid physical labour performed by farmer and family members, calculated at statutory agricultural wage rates',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'State Agricultural Wages / CACP Comprehensive Scheme',
    sourceDate: '2024-2025',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'imputed_rental_owned_land',
    name: 'Imputed Rental Value of Owned Land',
    description: 'Opportunity rent of owned land (net of land revenue)',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'CACP Comprehensive Scheme (Cost B2 Concept)',
    sourceDate: '2024-2025',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'imputed_interest_owned_capital',
    name: 'Imputed Interest on Owned Fixed Capital',
    description: 'Interest on owned capital assets (excluding land)',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'CACP Comprehensive Scheme (Cost B1 Concept)',
    sourceDate: '2024-2025',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'production_volume_qtl',
    name: 'Total Crop Production in Quintals',
    description: 'Aggregate harvest yield measured in agricultural quintals (1 quintal = 100 kg)',
    dataType: 'number',
    unit: 'quintal',
    currency: null,
    required: true,
    minimum: 0,
    source: 'DES Farm Production Standard',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'seed_cost',
    name: 'Seed / Planting Material Cost',
    description: 'Expenditure on certified seeds or seedling nursery raising',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Farmer Input / DES Benchmark',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'fertilizer_cost',
    name: 'Chemical Fertilizer Cost',
    description: 'Expenditure on urea, DAP, MOP, SSP and micronutrients',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Farmer Input / DES Benchmark',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'manure_cost',
    name: 'Farmyard Manure (FYM) & Organic Inputs Cost',
    description: 'Cost of farmyard manure, compost, vermicompost, and bio-fertilizers',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Farmer Input / DES Benchmark',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'pesticide_cost',
    name: 'Plant Protection & Chemical Cost',
    description: 'Cost of insecticides, fungicides, weedicides and biological pest control',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Farmer Input / DES Benchmark',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'hired_labour_cost',
    name: 'Hired Labour Wages Cost',
    description: 'Actual wages paid in cash and kind to casual and attached hired farm labour',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Farmer Input / State Statutory Agricultural Wages',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'machine_cost',
    name: 'Machinery & Bullock Labour Cost',
    description: 'Tractor hiring, land preparation machinery, implements, and fuel expenses',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Custom Hiring Centre (CHC) Rates / DES Benchmark',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'irrigation_cost',
    name: 'Irrigation & Pumping Cost',
    description: 'Canal water charges, tubewell electricity tariff, diesel fuel, and micro-irrigation maintenance',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'State Irrigation Dept / Farmer Input',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'post_harvest_cost',
    name: 'Harvesting, Threshing & Packaging Cost',
    description: 'Expenses on harvesting, threshing, cleaning, sorting, bagging, and gunny bags',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Mandi / APMC Operational Norms',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'transport_cost',
    name: 'Produce Transport to APMC Mandi Cost',
    description: 'Freight, tractor trolley haulage, and loading/unloading from farm gate to market',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'Local Freight / Mandi Survey',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'misc_operational_cost',
    name: 'Land Revenue & Miscellaneous Expenses',
    description: 'Land revenue taxes, cesses, depreciation on farm implements, and working capital interest',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'CACP Cost Concept A1 Standard',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },
  {
    parameterId: 'realized_price_per_qtl',
    name: 'Realized Mandi Selling Price per Quintal',
    description: 'Wholesale APMC auction modal rate or farmgate selling price realized per quintal',
    dataType: 'number',
    unit: 'INR/quintal',
    currency: 'INR',
    required: true,
    minimum: 0,
    source: 'AGMARKNET / Market Reconciliation Engine or Farmer Input',
    sourceDate: '2024-2026',
    dataStatus: 'VERIFIED_DATA',
    userInputAllowed: true
  },
  {
    parameterId: 'byproduct_revenue',
    name: 'Byproduct / Residue / Fodder Revenue',
    description: 'Gross income from secondary crop residue, straw, stalks, or husk',
    dataType: 'number',
    unit: 'INR',
    currency: 'INR',
    required: false,
    minimum: 0,
    source: 'DES Farm Management Standard (typically 5-10% of main grain value)',
    sourceDate: '2024-2026',
    dataStatus: 'CALCULATED',
    userInputAllowed: true
  },

  // FoodTech Parameters
  {
    parameterId: 'raw_material_intake',
    name: 'Raw Material Intake',
    description: 'Total weight of unprocessed agro-produce fed into the processing facility',
    dataType: 'number',
    unit: 'kg',
    currency: null,
    required: true,
    minimum: 0,
    source: 'Plant Processing Intake Records',
    sourceDate: '2024-2026',
    dataStatus: 'USER_INPUT',
    userInputAllowed: true
  },
  {
    parameterId: 'finished_goods_target',
    name: 'Finished Packaged Output Target',
    description: 'Target packaged finished goods volume required for distribution',
    dataType: 'number',
    unit: 'kg',
    currency: null,
    required: true,
    minimum: 0,
    source: 'Sales Demand Target',
    sourceDate: '2024-2026',
    dataStatus: 'USER_INPUT',
    userInputAllowed: true
  },
  {
    parameterId: 'processing_loss_pct',
    name: 'Processing & Handling Loss %',
    description: 'Moisture loss, dust extraction, cleaning residue, and conveyance spillage percentage',
    dataType: 'number',
    unit: 'PERCENT',
    currency: null,
    required: true,
    minimum: 0,
    maximum: 50,
    source: 'CSIR-CFTRI Post-Harvest Technology Norms',
    sourceDate: '2023-2025',
    dataStatus: 'VERIFIED_DATA',
    userInputAllowed: true
  },
  {
    parameterId: 'recovery_rate_pct',
    name: 'Extraction / Recovery Rate %',
    description: 'Standard product yield conversion ratio (e.g. 96% for flour milling, 72% for dal milling, 38% for mustard oil)',
    dataType: 'number',
    unit: 'PERCENT',
    currency: null,
    required: true,
    minimum: 1,
    maximum: 100,
    source: 'MoFPI PMFME Project Profiles & NABARD Benchmarks',
    sourceDate: '2024-2026',
    dataStatus: 'VERIFIED_DATA',
    userInputAllowed: true
  },
  {
    parameterId: 'byproduct_recovery_pct',
    name: 'Byproduct Extraction Rate %',
    description: 'Saleable secondary product recovery ratio (e.g. wheat bran / chokar, oil cake, husk)',
    dataType: 'number',
    unit: 'PERCENT',
    currency: null,
    required: true,
    minimum: 0,
    maximum: 99,
    source: 'NABARD Agro-Processing Sectoral Norms',
    sourceDate: '2024-2026',
    dataStatus: 'VERIFIED_DATA',
    userInputAllowed: true
  }
];

const INITIAL_FORMULAS = [
  // ─── 1. CORE FINANCIAL PRIMITIVES (ICAI, ICMAI, RBI, NABARD) ───
  {
    formulaId: 'FIN_REVENUE',
    formulaName: 'Total Gross Sales Revenue',
    description: 'Calculates gross operational revenue generated from the sale of goods or services.',
    category: 'FINANCE',
    expression: 'selling_price * quantity_sold',
    inputs: ['selling_price', 'quantity_sold'],
    outputs: ['revenue'],
    units: { selling_price: 'INR/unit', quantity_sold: 'units', revenue: 'INR' },
    assumptions: ['All produced units sold at uniform average realized rate', 'Excludes indirect output taxes (GST)'],
    source: 'Institute of Chartered Accountants of India (ICAI) — Accounting Standard (AS) 9: Revenue Recognition',
    sourceURL: 'https://www.icai.org/post/accounting-standard-as-9',
    sourceDate: '2024-01-01',
    methodology: 'Gross inflow of economic benefits arising in the ordinary course of business from the sale of goods (AS-9 clause 4.1).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['selling_price >= 0', 'quantity_sold >= 0']
  },
  {
    formulaId: 'FIN_TOTAL_COST',
    formulaName: 'Total Operational Cost',
    description: 'Calculates aggregate enterprise cost as the summation of fixed overheads and variable operating expenses.',
    category: 'FINANCE',
    expression: 'fixed_cost + variable_cost',
    inputs: ['fixed_cost', 'variable_cost'],
    outputs: ['total_cost'],
    units: { fixed_cost: 'INR', variable_cost: 'INR', total_cost: 'INR' },
    assumptions: ['Linear cost behavior over the relevant operational output range'],
    source: 'Institute of Cost Accountants of India (ICMAI) — Cost Accounting Standard (CAS) 1: Classification of Cost',
    sourceURL: 'https://icmai.in/upload/Technical/CAS-1.pdf',
    sourceDate: '2024-01-01',
    methodology: 'Total cost represents aggregate expenditure incurred in business operations, segmented into fixed and variable components (CAS-1 clause 4.3).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['fixed_cost >= 0', 'variable_cost >= 0']
  },
  {
    formulaId: 'FIN_GROSS_PROFIT',
    formulaName: 'Gross Operating Profit',
    description: 'Calculates surplus revenue remaining after deducting direct variable operating expenses.',
    category: 'FINANCE',
    expression: 'revenue - variable_cost',
    inputs: ['revenue', 'variable_cost'],
    outputs: ['gross_profit'],
    units: { revenue: 'INR', variable_cost: 'INR', gross_profit: 'INR' },
    assumptions: ['Direct variable costs accurately matched to period revenue'],
    source: 'ICMAI Cost Accounting Standard CAS-4: Cost of Production Determination',
    sourceURL: 'https://icmai.in/upload/Technical/CAS-4.pdf',
    sourceDate: '2024-01-01',
    methodology: 'Gross margin available before amortization of period overheads and administrative fixed burden.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['revenue >= 0', 'variable_cost >= 0']
  },
  {
    formulaId: 'FIN_NET_PROFIT',
    formulaName: 'Net Operating Profit',
    description: 'Calculates the net bottom-line financial surplus after absorbing all fixed and variable overheads.',
    category: 'FINANCE',
    expression: 'gross_profit - fixed_cost',
    inputs: ['gross_profit', 'fixed_cost'],
    outputs: ['net_profit'],
    units: { gross_profit: 'INR', fixed_cost: 'INR', net_profit: 'INR' },
    assumptions: ['All period overheads, maintenance, and administrative expenses accounted for'],
    source: 'Institute of Chartered Accountants of India (ICAI) — Accounting Standard (AS) 5: Net Profit or Loss for the Period',
    sourceURL: 'https://www.icai.org/post/accounting-standard-as-5',
    sourceDate: '2024-01-01',
    methodology: 'Net financial profit representing residual income from ordinary business activities after deducting total operational expenses.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['fixed_cost >= 0']
  },
  {
    formulaId: 'FIN_GROSS_MARGIN_PCT',
    formulaName: 'Gross Profit Margin Percentage',
    description: 'Measures the proportion of gross sales revenue retained as gross profit.',
    category: 'FINANCE',
    expression: 'round((gross_profit / revenue) * 100, 2)',
    inputs: ['gross_profit', 'revenue'],
    outputs: ['gross_margin_pct'],
    units: { gross_profit: 'INR', revenue: 'INR', gross_margin_pct: 'PERCENT' },
    assumptions: ['Revenue must be strictly greater than zero to prevent indeterminate ratio'],
    source: 'Reserve Bank of India (RBI) — Master Direction on Lending to Micro, Small & Medium Enterprises (MSME) Sector',
    sourceURL: 'https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10390',
    sourceDate: '2024-01-01',
    methodology: 'Standard financial ratio indicating commercial pricing efficiency and variable expense cushion.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['revenue > 0']
  },
  {
    formulaId: 'FIN_NET_MARGIN_PCT',
    formulaName: 'Net Profit Margin Percentage',
    description: 'Measures bottom-line net profit generated per rupee of revenue.',
    category: 'FINANCE',
    expression: 'round((net_profit / revenue) * 100, 2)',
    inputs: ['net_profit', 'revenue'],
    outputs: ['net_margin_pct'],
    units: { net_profit: 'INR', revenue: 'INR', net_margin_pct: 'PERCENT' },
    assumptions: ['Revenue must be strictly greater than zero'],
    source: 'Reserve Bank of India (RBI) — Master Direction on Lending to MSME Sector (Credit Appraisal Framework)',
    sourceURL: 'https://www.rbi.org.in/Scripts/BS_ViewMasDirections.aspx?id=10390',
    sourceDate: '2024-01-01',
    methodology: 'Standard commercial ratio indicating enterprise net earning capacity relative to total turnover.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['revenue > 0']
  },
  {
    formulaId: 'FIN_BREAK_EVEN_QUANTITY',
    formulaName: 'Break-Even Production Volume',
    description: 'Calculates the threshold unit sales volume required to cover all operational fixed and variable costs without profit or loss.',
    category: 'FINANCE',
    expression: 'round(fixed_cost / (selling_price - variable_cost_per_unit), 2)',
    inputs: ['fixed_cost', 'selling_price', 'variable_cost_per_unit'],
    outputs: ['break_even_quantity'],
    units: { fixed_cost: 'INR', selling_price: 'INR/unit', variable_cost_per_unit: 'INR/unit', break_even_quantity: 'units' },
    assumptions: ['Unit selling price exceeds unit variable cost (positive unit contribution margin)', 'Fixed costs remain invariant over output range'],
    source: 'Institute of Cost Accountants of India (ICMAI) — Cost Volume Profit (CVP) Analysis Framework',
    sourceURL: 'https://icmai.in/upload/Technical/CVP_Framework.pdf',
    sourceDate: '2024-01-01',
    methodology: 'Break-Even Units = Total Fixed Cost / (Unit Selling Price - Unit Variable Cost), where denominator is unit contribution margin.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['selling_price > variable_cost_per_unit', 'fixed_cost >= 0']
  },
  {
    formulaId: 'FIN_WORKING_CAPITAL_OPERATING_CYCLE',
    formulaName: 'Working Capital Requirement (Operating Cycle Method)',
    description: 'Calculates required liquidity buffer based on operating cycle length and daily operational run-rate.',
    category: 'FINANCE',
    expression: 'round((annual_operating_cost / 365) * operating_cycle_days, 2)',
    inputs: ['annual_operating_cost', 'operating_cycle_days'],
    outputs: ['working_capital_required'],
    units: { annual_operating_cost: 'INR/year', operating_cycle_days: 'days', working_capital_required: 'INR' },
    assumptions: ['Operational cash outflows distributed relatively evenly throughout the 365-day year', 'Operating cycle captures inventory holding + receivable collection lag'],
    source: 'Reserve Bank of India (RBI) — Nayak Committee Guidelines on Working Capital Assessment for Village & SSI Units',
    sourceURL: 'https://www.rbi.org.in/scripts/PublicationReportDetails.aspx?ID=18',
    sourceDate: '2024-01-01',
    methodology: 'Working capital computed as daily operating expenditure multiplied by the operating cycle turnaround duration in days.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['annual_operating_cost >= 0', 'operating_cycle_days >= 1', 'operating_cycle_days <= 365']
  },
  {
    formulaId: 'FIN_ROI_PCT',
    formulaName: 'Return on Capital Investment Percentage (ROI)',
    description: 'Calculates the annual return generated on total capital invested in the enterprise.',
    category: 'FINANCE',
    expression: 'round((net_profit / initial_investment) * 100, 2)',
    inputs: ['net_profit', 'initial_investment'],
    outputs: ['roi_pct'],
    units: { net_profit: 'INR', initial_investment: 'INR', roi_pct: 'PERCENT' },
    assumptions: ['Initial investment captures total project capital expenditure plus initial working capital margin', 'Investment must be greater than zero'],
    source: 'NABARD Project Formulation & Appraisal Manual (Financial Evaluation Techniques)',
    sourceURL: 'https://www.nabard.org/content1.aspx?id=594&catid=23&mid=530',
    sourceDate: '2024-01-01',
    methodology: 'Standard accounting rate of return expressing annual net operational surplus as a percentage of initial capital outlay.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['initial_investment > 0']
  },
  {
    formulaId: 'FIN_SIMPLE_PAYBACK_PERIOD',
    formulaName: 'Simple Payback Period',
    description: 'Calculates the number of years required to recover initial capital investment from net annual operating cash flow.',
    category: 'FINANCE',
    expression: 'round(initial_investment / net_annual_cashflow, 2)',
    inputs: ['initial_investment', 'net_annual_cashflow'],
    outputs: ['payback_period_years'],
    units: { initial_investment: 'INR', net_annual_cashflow: 'INR/year', payback_period_years: 'years' },
    assumptions: ['Net annual cash flow is positive', 'Cash inflows remain steady over the initial recovery period'],
    source: 'NABARD Model Bankable Projects Appraisal Standards',
    sourceURL: 'https://www.nabard.org/content1.aspx?id=594&catid=23&mid=530',
    sourceDate: '2024-01-01',
    methodology: 'Time horizon in years where cumulative net operating surplus equals original capital invested.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['initial_investment > 0', 'net_annual_cashflow > 0']
  },

  // ─── 2. AGRICULTURE & CROP CULTIVATION (CACP, DES, MoAFW) ───
  {
    formulaId: 'AGRI_TOTAL_PRODUCTION',
    formulaName: 'Total Crop Production Volume',
    description: 'Calculates gross harvest volume from cultivated land area and average yield.',
    category: 'AGRICULTURE',
    expression: 'round(area_ha * yield_tonnes_per_ha, 2)',
    inputs: ['area_ha', 'yield_tonnes_per_ha'],
    outputs: ['total_production_tonnes'],
    units: { area_ha: 'hectare', yield_tonnes_per_ha: 'tonnes/ha', total_production_tonnes: 'tonnes' },
    assumptions: ['Uniform yield realization across cultivated parcel', 'Zero total crop failure'],
    source: 'Directorate of Economics & Statistics (DES), Ministry of Agriculture & Farmers Welfare — Agricultural Statistics at a Glance',
    sourceURL: 'https://eands.dacnet.nic.in/Publication12-12-2023/Agricultural_Statistics_at_a_Glance_2022.pdf',
    sourceDate: '2023-12-01',
    methodology: 'Standard agricultural production identity: Output (Q) = Net Area Sown (A) × Average Yield (Y).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['area_ha > 0', 'yield_tonnes_per_ha >= 0']
  },
  {
    formulaId: 'AGRI_CACP_COST_A2',
    formulaName: 'CACP Cost A2 (Paid-Out Costs + Leased Land Rent)',
    description: 'Calculates CACP Cost A2 covering all cash/in-kind expenses on seeds, fertilizers, chemicals, labor, fuel, machinery, plus actual rent paid for leased-in land.',
    category: 'AGRICULTURE',
    expression: 'paid_out_operational_expenses + rent_paid_leased_in_land',
    inputs: ['paid_out_operational_expenses', 'rent_paid_leased_in_land'],
    outputs: ['cost_a2'],
    units: { paid_out_operational_expenses: 'INR', rent_paid_leased_in_land: 'INR', cost_a2: 'INR' },
    assumptions: ['Captures direct out-of-pocket operational cash/kind costs incurred by the farmer'],
    source: 'Commission for Agricultural Costs & Prices (CACP), Ministry of Agriculture & Farmers Welfare — Cost Concepts and Methodology',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Cost A2 = Cost A1 (all actual paid out expenses on inputs, hired labor, machinery, irrigation) + Rent paid for leased in land (CACP Cost Concept A2).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['paid_out_operational_expenses >= 0', 'rent_paid_leased_in_land >= 0']
  },
  {
    formulaId: 'AGRI_CACP_COST_A2_FL',
    formulaName: 'CACP Cost A2+FL (Cost A2 + Imputed Family Labour)',
    description: 'Calculates statutory cost concept A2+FL used by the Government of India as the primary benchmark for Minimum Support Price (MSP) fixation (ensuring at least 50% margin over A2+FL).',
    category: 'AGRICULTURE',
    expression: 'cost_a2 + imputed_family_labour_value',
    inputs: ['cost_a2', 'imputed_family_labour_value'],
    outputs: ['cost_a2_fl'],
    units: { cost_a2: 'INR', imputed_family_labour_value: 'INR', cost_a2_fl: 'INR' },
    assumptions: ['Family labor hours evaluated at prevailing state statutory agricultural wage rates'],
    source: 'Commission for Agricultural Costs & Prices (CACP) & National Commission on Farmers (Swaminathan Committee Report, 2006)',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Statutory basis for GoI Union Budget 2018-19 MSP policy (MSP = Cost A2+FL × 1.50). Sum of paid out expenses (Cost A2) and imputed value of family labour (FL).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_a2 >= 0', 'imputed_family_labour_value >= 0']
  },
  {
    formulaId: 'AGRI_CACP_COMPREHENSIVE_COST_C2',
    formulaName: 'CACP Comprehensive Cost C2',
    description: 'Calculates the complete comprehensive economic cost of cultivation, including Cost A2+FL plus imputed interest on owned capital assets and rental value of owned land.',
    category: 'AGRICULTURE',
    expression: 'cost_a2_fl + imputed_interest_owned_capital + imputed_rental_owned_land',
    inputs: ['cost_a2_fl', 'imputed_interest_owned_capital', 'imputed_rental_owned_land'],
    outputs: ['cost_c2'],
    units: { cost_a2_fl: 'INR', imputed_interest_owned_capital: 'INR', imputed_rental_owned_land: 'INR', cost_c2: 'INR' },
    assumptions: ['Interest calculated on market value of owned farm implements; opportunity rent estimated net of land tax'],
    source: 'Commission for Agricultural Costs & Prices (CACP) — Price Policy Reports (Comprehensive Cost C2)',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Cost C2 = Cost B2 + Imputed value of family labour = Cost A2 + Family labour + Interest on owned capital + Rental value of owned land.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_a2_fl >= 0', 'imputed_interest_owned_capital >= 0', 'imputed_rental_owned_land >= 0']
  },
  {
    formulaId: 'AGRI_BREAK_EVEN_MANDI_PRICE',
    formulaName: 'Break-Even Mandi Modal Price per Quintal',
    description: 'Calculates the minimum auction price per quintal required in APMC mandis to fully recover comprehensive Cost C2.',
    category: 'AGRICULTURE',
    expression: 'round(cost_c2 / production_volume_qtl, 2)',
    inputs: ['cost_c2', 'production_volume_qtl'],
    outputs: ['break_even_price_per_qtl'],
    units: { cost_c2: 'INR', production_volume_qtl: 'quintal', break_even_price_per_qtl: 'INR/quintal' },
    assumptions: ['Production volume strictly greater than zero; single-crop allocation without multi-crop joint cost distortion'],
    source: 'CACP Comprehensive Cost of Production Standard (C2/Qtl Basis)',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Unit Cost of Production = Total Comprehensive Cost C2 / Total Produce Harvested in Quintals.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_c2 >= 0', 'production_volume_qtl > 0']
  },
  {
    formulaId: 'AGRI_TOTAL_PRODUCTION_QTL',
    formulaName: 'Total Crop Production in Quintals',
    description: 'Converts production volume from metric tonnes to standard agricultural quintals (1 Tonne = 10 Quintals).',
    category: 'AGRICULTURE',
    expression: 'round(total_production_tonnes * 10, 2)',
    inputs: ['total_production_tonnes'],
    outputs: ['production_volume_qtl'],
    units: { total_production_tonnes: 'tonnes', production_volume_qtl: 'quintal' },
    assumptions: ['Standard metric conversion factor: 1 Tonne = 1000 kg = 10 Quintals'],
    source: 'Directorate of Economics & Statistics (DES) Agricultural Statistics Metric Standards',
    sourceURL: 'https://eands.dacnet.nic.in/',
    sourceDate: '2024-01-01',
    methodology: 'Output in Quintals = Output in Metric Tonnes × 10.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['total_production_tonnes >= 0']
  },
  {
    formulaId: 'AGRI_CACP_COST_A1',
    formulaName: 'CACP Cost A1 (All Direct Paid-Out Operational Expenses)',
    description: 'Calculates statutory CACP Cost A1 covering all direct cash and kind operational expenditures on seed, fertilizer, manure, pesticides, hired labor, machinery, irrigation, post-harvest, transport, and depreciation.',
    category: 'AGRICULTURE',
    expression: 'seed_cost + fertilizer_cost + manure_cost + pesticide_cost + hired_labour_cost + machine_cost + irrigation_cost + post_harvest_cost + transport_cost + misc_operational_cost',
    inputs: [
      'seed_cost', 'fertilizer_cost', 'manure_cost', 'pesticide_cost',
      'hired_labour_cost', 'machine_cost', 'irrigation_cost',
      'post_harvest_cost', 'transport_cost', 'misc_operational_cost'
    ],
    outputs: ['cost_a1'],
    units: { cost_a1: 'INR' },
    assumptions: ['Aggregates all direct variable and paid-out cultivation expenses incurred in the season'],
    source: 'Commission for Agricultural Costs & Prices (CACP) — Cost Concepts and Methodology (Cost A1)',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Cost A1 = Value of hired human labour + bullock labour + machine labour + seed + fertilizers and manure + plant protection chemicals + irrigation charges + depreciation on farm implements + land revenue and cesses + interest on working capital + miscellaneous expenses.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_a1 >= 0']
  },
  {
    formulaId: 'AGRI_CACP_COST_B1',
    formulaName: 'CACP Cost B1 (Cost A1 + Interest on Owned Capital)',
    description: 'Calculates CACP Cost B1 representing Cost A1 plus imputed interest on owned fixed capital assets (excluding land).',
    category: 'AGRICULTURE',
    expression: 'cost_a1 + imputed_interest_owned_capital',
    inputs: ['cost_a1', 'imputed_interest_owned_capital'],
    outputs: ['cost_b1'],
    units: { cost_a1: 'INR', imputed_interest_owned_capital: 'INR', cost_b1: 'INR' },
    assumptions: ['Interest evaluated at standard prevailing agricultural borrowing interest rates'],
    source: 'Commission for Agricultural Costs & Prices (CACP) — Cost Concepts and Methodology (Cost B1)',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Cost B1 = Cost A1 + Imputed interest on value of owned capital assets (excluding land).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_a1 >= 0', 'imputed_interest_owned_capital >= 0']
  },
  {
    formulaId: 'AGRI_CACP_COST_B2',
    formulaName: 'CACP Cost B2 (Cost B1 + Rental Value of Owned Land)',
    description: 'Calculates CACP Cost B2 representing Cost B1 plus imputed rental value of owned land (net of land revenue).',
    category: 'AGRICULTURE',
    expression: 'cost_b1 + imputed_rental_owned_land',
    inputs: ['cost_b1', 'imputed_rental_owned_land'],
    outputs: ['cost_b2'],
    units: { cost_b1: 'INR', imputed_rental_owned_land: 'INR', cost_b2: 'INR' },
    assumptions: ['Opportunity rental value assessed based on prevailing local agricultural lease rates'],
    source: 'Commission for Agricultural Costs & Prices (CACP) — Cost Concepts and Methodology (Cost B2)',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Cost B2 = Cost B1 + Rental value of owned land (net of land revenue) + Rent paid for leased-in land.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_b1 >= 0', 'imputed_rental_owned_land >= 0']
  },
  {
    formulaId: 'AGRI_CACP_COST_C1',
    formulaName: 'CACP Cost C1 (Cost B1 + Family Labour)',
    description: 'Calculates CACP Cost C1 representing Cost B1 plus imputed value of family labour.',
    category: 'AGRICULTURE',
    expression: 'cost_b1 + imputed_family_labour_value',
    inputs: ['cost_b1', 'imputed_family_labour_value'],
    outputs: ['cost_c1'],
    units: { cost_b1: 'INR', imputed_family_labour_value: 'INR', cost_c1: 'INR' },
    assumptions: ['Family labour valued at statutory agricultural wage rates'],
    source: 'Commission for Agricultural Costs & Prices (CACP) — Cost Concepts and Methodology (Cost C1)',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Cost C1 = Cost B1 + Imputed value of family labour.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_b1 >= 0', 'imputed_family_labour_value >= 0']
  },
  {
    formulaId: 'AGRI_MAIN_PRODUCE_REVENUE',
    formulaName: 'Gross Main Crop Produce Revenue',
    description: 'Calculates gross income from primary harvest output sold at realized mandi modal rate.',
    category: 'AGRICULTURE',
    expression: 'round(production_volume_qtl * realized_price_per_qtl, 2)',
    inputs: ['production_volume_qtl', 'realized_price_per_qtl'],
    outputs: ['main_produce_revenue'],
    units: { production_volume_qtl: 'quintal', realized_price_per_qtl: 'INR/quintal', main_produce_revenue: 'INR' },
    assumptions: ['Whole harvest produce valued at realized auction modal rate'],
    source: 'Directorate of Economics & Statistics (DES) / APMC Farm Accounting Standards',
    sourceURL: 'https://eands.dacnet.nic.in/',
    sourceDate: '2024-01-01',
    methodology: 'Main Produce Revenue = Total Production (Quintals) × Realized Modal Price (INR/Quintal).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['production_volume_qtl >= 0', 'realized_price_per_qtl >= 0']
  },
  {
    formulaId: 'AGRI_TOTAL_REVENUE',
    formulaName: 'Total Agricultural Farm Revenue',
    description: 'Calculates aggregate crop enterprise revenue combining main grain produce and saleable byproducts (fodder, straw, residue).',
    category: 'AGRICULTURE',
    expression: 'round(main_produce_revenue + byproduct_revenue, 2)',
    inputs: ['main_produce_revenue', 'byproduct_revenue'],
    outputs: ['total_revenue'],
    units: { main_produce_revenue: 'INR', byproduct_revenue: 'INR', total_revenue: 'INR' },
    assumptions: ['Byproduct revenue derived from local fodder/residue sale'],
    source: 'ICAI AS-9 / DES Farm Management Survey Methodology',
    sourceURL: 'https://eands.dacnet.nic.in/',
    sourceDate: '2024-01-01',
    methodology: 'Total Farm Revenue = Main Produce Revenue + Byproduct Residue Revenue.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['main_produce_revenue >= 0', 'byproduct_revenue >= 0']
  },
  {
    formulaId: 'AGRI_FARM_BUSINESS_INCOME',
    formulaName: 'Farm Business Income (Return over Cost A2)',
    description: 'Calculates actual cash operating surplus available to the farming family after covering all direct paid-out expenditures (Cost A2).',
    category: 'AGRICULTURE',
    expression: 'round(total_revenue - cost_a2, 2)',
    inputs: ['total_revenue', 'cost_a2'],
    outputs: ['farm_business_income'],
    units: { total_revenue: 'INR', cost_a2: 'INR', farm_business_income: 'INR' },
    assumptions: ['Reflects actual cash surplus to farmer for family living and capital formation'],
    source: 'CACP Farm Management Surveys & Agricultural Income Concepts',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Farm Business Income = Gross Revenue - Cost A2 (actual paid-out operational costs).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_a2 >= 0']
  },
  {
    formulaId: 'AGRI_NET_ECONOMIC_PROFIT',
    formulaName: 'Net Economic Profit (Return over Comprehensive Cost C2)',
    description: 'Calculates pure economic surplus remaining after deducting comprehensive economic Cost C2 (including opportunity cost of family labour, owned land, and owned capital).',
    category: 'AGRICULTURE',
    expression: 'round(total_revenue - cost_c2, 2)',
    inputs: ['total_revenue', 'cost_c2'],
    outputs: ['net_profit'],
    units: { total_revenue: 'INR', cost_c2: 'INR', net_profit: 'INR' },
    assumptions: ['Comprehensive economic accounting: surplus above market return on all owned and hired factors of production'],
    source: 'CACP Net Returns Methodology & ICAI AS-5 Standards',
    sourceURL: 'https://cacp.dacnet.nic.in/Content.aspx?DocId=1&PID=28',
    sourceDate: '2024-05-01',
    methodology: 'Net Economic Return = Gross Revenue - Cost C2.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['cost_c2 >= 0']
  },
  {
    formulaId: 'AGRI_BENEFIT_COST_RATIO',
    formulaName: 'Crop Benefit-Cost Ratio (BCR)',
    description: 'Measures gross revenue earned per rupee of comprehensive cultivation expenditure (Cost C2).',
    category: 'AGRICULTURE',
    expression: 'round(total_revenue / cost_c2, 2)',
    inputs: ['total_revenue', 'cost_c2'],
    outputs: ['benefit_cost_ratio'],
    units: { total_revenue: 'INR', cost_c2: 'INR', benefit_cost_ratio: 'ratio' },
    assumptions: ['Cost C2 must be strictly greater than zero; BCR >= 1.50 represents high economic feasibility'],
    source: 'NABARD Agricultural Project Formulation & Appraisal Manual',
    sourceURL: 'https://www.nabard.org/content1.aspx?id=594&catid=23&mid=530',
    sourceDate: '2024-01-01',
    methodology: 'BCR = Gross Farm Revenue / Total Comprehensive Cost C2.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['total_revenue >= 0', 'cost_c2 > 0']
  },
  {
    formulaId: 'AGRI_CROP_WATER_EVAPOTRANSPIRATION',
    formulaName: 'Crop Evapotranspiration Water Demand',
    description: 'Calculates seasonal agronomic water requirement based on reference evapotranspiration and crop stage coefficient.',
    category: 'AGRICULTURE',
    expression: 'round(crop_reference_et0 * crop_coefficient_kc, 2)',
    inputs: ['crop_reference_et0', 'crop_coefficient_kc'],
    outputs: ['crop_evapotranspiration_mm'],
    units: { crop_reference_et0: 'mm/day', crop_coefficient_kc: 'ratio', crop_evapotranspiration_mm: 'mm/day' },
    assumptions: ['Penman-Monteith reference ET0 valid for local agro-climatic zone'],
    source: 'FAO Irrigation and Drainage Paper No. 56 / ICAR Water Technology Centre',
    sourceURL: 'https://www.fao.org/3/x0490e/x0490e00.htm',
    sourceDate: '2023-01-01',
    methodology: 'ETc = Kc × ET0. Requires dynamic local agrometeorological integration before authoritative production use.',
    status: FORMULA_STATUSES.RESEARCH_REQUIRED, // Explicitly marked RESEARCH_REQUIRED as per user instructions
    version: '1.0.0',
    validationRules: ['crop_reference_et0 > 0', 'crop_coefficient_kc > 0']
  },

  // ─── 3. FOODTECH & AGRO-PROCESSING (MoFPI, NABARD, CSIR-CFTRI) ───
  {
    formulaId: 'FOODTECH_RAW_MATERIAL_REQUIREMENT',
    formulaName: 'Gross Raw Material Procurement Requirement',
    description: 'Calculates the gross raw agricultural produce intake required to achieve a finished packaged output target, taking into account processing loss and recovery rate.',
    category: 'FOODTECH',
    expression: 'round(finished_goods_target / ((1 - (processing_loss_pct / 100)) * (recovery_rate_pct / 100)), 2)',
    inputs: ['finished_goods_target', 'processing_loss_pct', 'recovery_rate_pct'],
    outputs: ['raw_material_intake_required'],
    units: { finished_goods_target: 'kg', processing_loss_pct: 'PERCENT', recovery_rate_pct: 'PERCENT', raw_material_intake_required: 'kg' },
    assumptions: ['Loss and recovery percentages are constant within the standard operating capacity window', 'Recovery rate > 0 and Processing loss < 100%'],
    source: 'Ministry of Food Processing Industries (MoFPI) — PMFME Model DPR / CSIR-CFTRI Food Engineering Standards',
    sourceURL: 'https://pmfme.mofpi.gov.in/pmfme/#/Home-Page',
    sourceDate: '2024-03-01',
    methodology: 'Mass Balance Equation: Target Output = Raw Material × (1 - Processing Loss Fraction) × Recovery Fraction. Solved for Raw Material.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['finished_goods_target > 0', 'processing_loss_pct >= 0', 'processing_loss_pct < 100', 'recovery_rate_pct > 0', 'recovery_rate_pct <= 100']
  },
  {
    formulaId: 'FOODTECH_FINISHED_GOODS_OUTPUT',
    formulaName: 'Net Packaged Finished Goods Yield',
    description: 'Calculates the net salable packaged product yield obtained from a given intake of raw material.',
    category: 'FOODTECH',
    expression: 'round(raw_material_intake * (1 - (processing_loss_pct / 100)) * (recovery_rate_pct / 100), 2)',
    inputs: ['raw_material_intake', 'processing_loss_pct', 'recovery_rate_pct'],
    outputs: ['net_finished_product_kg'],
    units: { raw_material_intake: 'kg', processing_loss_pct: 'PERCENT', recovery_rate_pct: 'PERCENT', net_finished_product_kg: 'kg' },
    assumptions: ['Standard operating recovery efficiency with continuous destoning and cleaning'],
    source: 'CSIR-Central Food Technological Research Institute (CFTRI) — Process Technology Profiles',
    sourceURL: 'https://cftri.res.in/technologies',
    sourceDate: '2024-01-01',
    methodology: 'Yield conversion standard: Net Output = Intake × (1 - Loss Fraction) × Extraction Fraction.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['raw_material_intake >= 0', 'processing_loss_pct >= 0', 'recovery_rate_pct > 0']
  },
  {
    formulaId: 'FOODTECH_BYPRODUCT_OUTPUT',
    formulaName: 'Secondary Salable Byproduct Yield',
    description: 'Calculates secondary commercial byproduct output (e.g. wheat bran/chokar, dal powder, oil cake) from raw material processing.',
    category: 'FOODTECH',
    expression: 'round(raw_material_intake * (byproduct_recovery_pct / 100), 2)',
    inputs: ['raw_material_intake', 'byproduct_recovery_pct'],
    outputs: ['byproduct_output_kg'],
    units: { raw_material_intake: 'kg', byproduct_recovery_pct: 'PERCENT', byproduct_output_kg: 'kg' },
    assumptions: ['Byproduct separation efficiency adheres to commercial milling machinery specifications'],
    source: 'NABARD Model Bankable Projects — Micro Agro-Processing & Dal/Flour Milling Guidelines 2024',
    sourceURL: 'https://www.nabard.org/content1.aspx?id=594&catid=23&mid=530',
    sourceDate: '2024-01-01',
    methodology: 'Byproduct Volume = Intake Volume × Byproduct Extraction Fraction (e.g. 4% chokar from wheat milling; 25% husk/chuni from pulses).',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['raw_material_intake >= 0', 'byproduct_recovery_pct >= 0']
  },
  {
    formulaId: 'FOODTECH_UNIT_PROCESSING_COST',
    formulaName: 'Unit Conversion Processing Cost',
    description: 'Calculates the processing cost incurred per kilogram of packaged output produced.',
    category: 'FOODTECH',
    expression: 'round(total_processing_cost / finished_goods_produced, 2)',
    inputs: ['total_processing_cost', 'finished_goods_produced'],
    outputs: ['unit_processing_cost_per_kg'],
    units: { total_processing_cost: 'INR', finished_goods_produced: 'kg', unit_processing_cost_per_kg: 'INR/kg' },
    assumptions: ['Captures milling power, operational labor, machinery maintenance, and packaging amortized across production volume'],
    source: 'ICMAI Cost Accounting Standard CAS-19: Joint and By-Product Costing / MoFPI Unit Costing Framework',
    sourceURL: 'https://icmai.in/upload/Technical/CAS-19.pdf',
    sourceDate: '2024-01-01',
    methodology: 'Unit Conversion Cost = Aggregate Operating Expenses Incurred in Conversion / Total Net Saleable Output.',
    status: FORMULA_STATUSES.VALIDATED,
    version: '1.0.0',
    validationRules: ['total_processing_cost >= 0', 'finished_goods_produced > 0']
  },
  {
    formulaId: 'FOODTECH_SHELF_LIFE_DECAY',
    formulaName: 'Food Product Kinetic Shelf-Life Degradation',
    description: 'Calculates deterioration rate of processed food commodities under variable ambient storage temperature.',
    category: 'FOODTECH',
    expression: 'round(base_rate * temp_factor, 4)',
    inputs: ['base_rate', 'temp_factor'],
    outputs: ['decay_rate_constant'],
    units: { base_rate: '1/day', temp_factor: 'ratio', decay_rate_constant: '1/day' },
    assumptions: ['First-order reaction kinetics (Arrhenius behavior)'],
    source: 'CSIR-CFTRI Post-Harvest Storage & Shelf-Life Kinetics Research',
    sourceURL: 'https://cftri.res.in/research-publications',
    sourceDate: '2023-05-01',
    methodology: 'k = k0 × exp(-Ea / RT). Requires lab testing of product activation energy Ea per product SKU before field deployment.',
    status: FORMULA_STATUSES.RESEARCH_REQUIRED, // Explicitly marked RESEARCH_REQUIRED as per user instructions
    version: '1.0.0',
    validationRules: ['base_rate > 0', 'temp_factor > 0']
  }
];

const { FOODTECH_PARAMETERS } = require('../business/foodtech/foodtechParameters');
const { FOODTECH_FORMULAS } = require('../business/foodtech/foodtechFormulas');

/**
 * Initializes and registers all curated parameters and formulas into a registry instance
 * 
 * @param {FormulaRegistry} registry
 */
function seedFormulaRegistry(registry) {
  for (const param of INITIAL_PARAMETERS) {
    registry.registerParameter(param);
  }

  for (const formula of INITIAL_FORMULAS) {
    registry.registerFormula(formula);
  }

  // Register verified FoodTech parameters and formulas
  for (const param of FOODTECH_PARAMETERS) {
    if (!registry.hasParameter(param.parameterId)) {
      registry.registerParameter(param);
    }
  }

  for (const formula of FOODTECH_FORMULAS) {
    if (!registry.hasFormula(formula.formulaId)) {
      registry.registerFormula(formula);
    }
  }

  return registry;
}

module.exports = {
  INITIAL_PARAMETERS,
  INITIAL_FORMULAS,
  seedFormulaRegistry
};
